FROM alpine:3.20.3

ENV PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/go/bin

WORKDIR /usr/share/heartbeat

COPY build/heartbeat /usr/share/heartbeat/heartbeat

ENTRYPOINT ["./heartbeat"]

CMD [ "-e" ]
